### ISSUE TITLE
指标计算的问题

### ISSUE THREAD

**Issue by liuli33** [ZhangJC-2k/DPU#2]
所提供的cal_psnr_ssim.m，计算psnr指标的代码好像与“https://github.com/caiyuanhao1998/MST”中的不一致，计算的结果也有0.2dB左右的区别，作者有发现这个问题吗？

**Comment by ZhangJC-2k** [comment]
感谢提问，我们也注意到了这个问题。这是由于我们和先前的方法（包括MSTseries）都是使用64位的数据去训练，MST在测试过程中将数据转化为了unit8格式，有一点精度下降，而我们采取原始64位数据去直接计算，因此会有一点差距。你可以将MST计算中的数据转化去掉并修改图象最大值为1得到相同结果。
