### ISSUE TITLE
作者能否提供一下测试结果

### ISSUE THREAD

**Issue by liuli33** [ZhangJC-2k/DPU#3]
作者好像没有提供真实场景的测试代码和结果，能否提供一下？方便对文章结果的引用？

**Comment by ZhangJC-2k** [comment]
感谢提醒，我们会尽快整理真实场景的结果和代码并放出。

**Comment by ZhangJC-2k** [comment]
哈喽，我们真实场景的结果已经放出，能够在[这里](https://pan.baidu.com/s/1xtv7YotNPS0lf7dcEWanFw?pwd=zuir)下载，请随意使用。

**Comment by liuli33** [comment]
十分感谢！
